vim.g.netrw_winsize = 20       -- size of the netrw window
vim.opt.fileformat = 'unix'    -- force unix
vim.opt.background = 'dark'    -- 'dark' or 'light', used for highlight colors
vim.opt.termguicolors = true   -- enable 24-bit RGB color in the TUI
vim.opt.backup = false         -- keep backup file after overwriting a file
vim.opt.writebackup = false    -- make a backup before overwriting a file
vim.opt.swapfile = false       -- whether to use a swapfile for a buffer
vim.opt.undofile = false       -- save undo history
vim.opt.clipboard = 'unnamedplus'  -- use the clipboard as the unnamed register
vim.opt.completeopt = 'menuone,noselect'  -- options for Insert mode completion
-- vim.opt.completeopt = 'menu,menuone,noinsert,preview'  -- options for Insert mode completion
vim.opt.wildmode = 'longest,list'  -- mode for 'wildchar' command-line expansion
vim.opt.hlsearch = true        -- highlight matches with last search pattern
vim.opt.ignorecase = true      -- ignore case in search patterns
vim.opt.smartcase = true       -- no ignore case when pattern has uppercase
vim.opt.mouse = 'a'            -- enable mouse in all modes
vim.opt.showmode = false       -- message on status line to show current mode
vim.opt.timeout = true         -- time out on mappings and key codes
vim.opt.timeoutlen = 300       -- time out time in milliseconds
vim.opt.updatetime = 250       -- after this many milliseconds flush swap file: 4000ms default
vim.opt.expandtab = true       -- use spaces when <Tab> is inserted
vim.opt.autoindent = true      -- take indent for new line from previous line
vim.opt.smartindent = true     -- smart autoindenting for C programs
vim.opt.tabstop = 4            -- number of spaces that <Tab> in file uses
vim.opt.softtabstop = 4        -- number of spaces that <Tab> uses while editing
vim.opt.shiftwidth = 4         -- number of spaces to use for (auto)indent step
vim.opt.cursorline = true      -- highlight the screen line of the cursor
vim.opt.cc = { 80, 120 }       -- columns to highlight
vim.opt.showmatch = true       -- briefly jump to matching bracket if insert one
vim.opt.number = true          -- print the line number in front of each line
-- vim.opt.relativenumber = true  -- show relative line number in front of each line
vim.opt.numberwidth = 2        -- number of columns used for the line number
vim.opt.signcolumn = 'yes'     -- when and how to display the sign column
-- vim.opt.wrap = false           -- long lines wrap and continue on the next line
vim.opt.breakindent = true     -- wrapped line repeats indent
vim.opt.linebreak = true       -- wrap long lines at a blank
vim.opt.formatoptions:remove { 'c', 'r', 'o' }  -- how automatic formatting is to be done
vim.opt.iskeyword:append '-'   -- characters included in keywords
--vim.opt.scrolloff = 8          -- minimum nr. of lines above and below cursor
--vim.opt.sidescrolloff = 8      -- min. nr. of columns to left and right of cursor
